import { combineReducers } from '@reduxjs/toolkit';
import {
  appointmentsBuilderReducer,
  allergiesBuilderReducer,
  conditionsBuilderReducer,
  dailyEntriesBuilderReducer,
  doctorsBuilderReducer,
  focusAreasBuilderReducer,
  healthImportBuilderReducer,
  hospitalsBuilderReducer,
  medicalHistoryEventsBuilderReducer,
  medicationsBuilderReducer,
  researchNotesBuilderReducer,
  specialtiesBuilderReducer,
  symptomLogsBuilderReducer,
  therapyExerciseImportBuilderReducer,
  therapyExercisesBuilderReducer,
  feedFormulasBuilderReducer,
  feedLogsBuilderReducer,
  morningCheckInBuilderReducer,
} from './builders';
import {
  currentAppointmentReducer,
  currentAllergyReducer,
  currentConditionReducer,
  currentDailyEntryReducer,
  currentDoctorReducer,
  currentFocusAreaReducer,
  currentHealthImportDraftReducer,
  currentHospitalReducer,
  currentMedicalHistoryEventReducer,
  currentMedicationReducer,
  currentResearchNoteReducer,
  currentSpecialtyReducer,
  currentSymptomLogReducer,
  currentTherapyExerciseReducer,
  currentFeedFormulaReducer,
  currentFeedLogReducer,
} from './current';
import {
  allergiesReducer,
  appointmentsReducer,
  clinicalNotesReducer,
  clinicalResultsReducer,
  conditionsReducer,
  dailyEntriesReducer,
  doctorsReducer,
  focusAreasReducer,
  healthImportsReducer,
  hospitalsReducer,
  insuranceCoveragesReducer,
  llmModelsReducer,
  medicalHistoryEventsReducer,
  medicationsReducer,
  referralsReducer,
  researchNotesReducer,
  specialtiesReducer,
  symptomDefinitionsReducer,
  symptomLogsReducer,
  therapyExerciseImportAiExchangesReducer,
  therapyExerciseLogsReducer,
  therapyExercisesReducer,
  feedFormulasReducer,
  feedLogsReducer,
  speechTherapyConsumptionReducer,
  vitalSignsReducer,
} from './dumps';

export const rootReducer = combineReducers({
  hospitals: hospitalsReducer,
  specialties: specialtiesReducer,
  doctors: doctorsReducer,
  appointments: appointmentsReducer,
  focusAreas: focusAreasReducer,
  dailyEntries: dailyEntriesReducer,
  medicalHistoryEvents: medicalHistoryEventsReducer,
  symptomDefinitions: symptomDefinitionsReducer,
  symptomLogs: symptomLogsReducer,
  researchNotes: researchNotesReducer,
  allergies: allergiesReducer,
  medications: medicationsReducer,
  conditions: conditionsReducer,
  vitalSigns: vitalSignsReducer,
  clinicalResults: clinicalResultsReducer,
  clinicalNotes: clinicalNotesReducer,
  referrals: referralsReducer,
  insuranceCoverages: insuranceCoveragesReducer,
  healthImports: healthImportsReducer,
  therapyExercises: therapyExercisesReducer,
  therapyExerciseLogs: therapyExerciseLogsReducer,
  feedFormulas: feedFormulasReducer,
  feedLogs: feedLogsReducer,
  speechTherapyConsumption: speechTherapyConsumptionReducer,
  llmModels: llmModelsReducer,
  therapyExerciseImportAiExchanges: therapyExerciseImportAiExchangesReducer,
  allergiesBuilder: allergiesBuilderReducer,
  medicationsBuilder: medicationsBuilderReducer,
  conditionsBuilder: conditionsBuilderReducer,
  hospitalsBuilder: hospitalsBuilderReducer,
  doctorsBuilder: doctorsBuilderReducer,
  appointmentsBuilder: appointmentsBuilderReducer,
  specialtiesBuilder: specialtiesBuilderReducer,
  focusAreasBuilder: focusAreasBuilderReducer,
  dailyEntriesBuilder: dailyEntriesBuilderReducer,
  medicalHistoryEventsBuilder: medicalHistoryEventsBuilderReducer,
  symptomLogsBuilder: symptomLogsBuilderReducer,
  researchNotesBuilder: researchNotesBuilderReducer,
  healthImportBuilder: healthImportBuilderReducer,
  therapyExerciseImportBuilder: therapyExerciseImportBuilderReducer,
  therapyExercisesBuilder: therapyExercisesBuilderReducer,
  feedFormulasBuilder: feedFormulasBuilderReducer,
  feedLogsBuilder: feedLogsBuilderReducer,
  morningCheckInBuilder: morningCheckInBuilderReducer,
  currentHospital: currentHospitalReducer,
  currentAllergy: currentAllergyReducer,
  currentMedication: currentMedicationReducer,
  currentCondition: currentConditionReducer,
  currentDoctor: currentDoctorReducer,
  currentAppointment: currentAppointmentReducer,
  currentSpecialty: currentSpecialtyReducer,
  currentFocusArea: currentFocusAreaReducer,
  currentDailyEntry: currentDailyEntryReducer,
  currentMedicalHistoryEvent: currentMedicalHistoryEventReducer,
  currentSymptomLog: currentSymptomLogReducer,
  currentResearchNote: currentResearchNoteReducer,
  currentHealthImportDraft: currentHealthImportDraftReducer,
  currentTherapyExercise: currentTherapyExerciseReducer,
  currentFeedFormula: currentFeedFormulaReducer,
  currentFeedLog: currentFeedLogReducer,
});
