import { combineReducers } from '@reduxjs/toolkit';
import {
  appointmentsBuilderReducer,
  dailyEntriesBuilderReducer,
  doctorsBuilderReducer,
  focusAreasBuilderReducer,
  hospitalsBuilderReducer,
  medicalHistoryEventsBuilderReducer,
  researchNotesBuilderReducer,
  specialtiesBuilderReducer,
  symptomLogsBuilderReducer,
} from './builders';
import {
  currentAppointmentReducer,
  currentDailyEntryReducer,
  currentDoctorReducer,
  currentFocusAreaReducer,
  currentHospitalReducer,
  currentMedicalHistoryEventReducer,
  currentResearchNoteReducer,
  currentSpecialtyReducer,
  currentSymptomLogReducer,
} from './current';
import {
  appointmentsReducer,
  dailyEntriesReducer,
  doctorsReducer,
  focusAreasReducer,
  hospitalsReducer,
  medicalHistoryEventsReducer,
  researchNotesReducer,
  specialtiesReducer,
  symptomLogsReducer,
} from './dumps';

export const rootReducer = combineReducers({
  hospitals: hospitalsReducer,
  specialties: specialtiesReducer,
  doctors: doctorsReducer,
  appointments: appointmentsReducer,
  focusAreas: focusAreasReducer,
  dailyEntries: dailyEntriesReducer,
  medicalHistoryEvents: medicalHistoryEventsReducer,
  symptomLogs: symptomLogsReducer,
  researchNotes: researchNotesReducer,
  hospitalsBuilder: hospitalsBuilderReducer,
  doctorsBuilder: doctorsBuilderReducer,
  appointmentsBuilder: appointmentsBuilderReducer,
  specialtiesBuilder: specialtiesBuilderReducer,
  focusAreasBuilder: focusAreasBuilderReducer,
  dailyEntriesBuilder: dailyEntriesBuilderReducer,
  medicalHistoryEventsBuilder: medicalHistoryEventsBuilderReducer,
  symptomLogsBuilder: symptomLogsBuilderReducer,
  researchNotesBuilder: researchNotesBuilderReducer,
  currentHospital: currentHospitalReducer,
  currentDoctor: currentDoctorReducer,
  currentAppointment: currentAppointmentReducer,
  currentSpecialty: currentSpecialtyReducer,
  currentFocusArea: currentFocusAreaReducer,
  currentDailyEntry: currentDailyEntryReducer,
  currentMedicalHistoryEvent: currentMedicalHistoryEventReducer,
  currentSymptomLog: currentSymptomLogReducer,
  currentResearchNote: currentResearchNoteReducer,
});
