export type { Appointment, AppointmentStatus } from './appointment';
export { EMPTY_APPOINTMENT } from './appointment';
export type { DailyEntry } from './daily-entry';
export { EMPTY_DAILY_ENTRY } from './daily-entry';
export type { Doctor } from './doctor';
export { EMPTY_DOCTOR } from './doctor';
export type { FocusArea } from './focus-area';
export { EMPTY_FOCUS_AREA } from './focus-area';
export type { Hospital } from './hospital';
export { EMPTY_HOSPITAL } from './hospital';
export type { Specialty } from './specialty';
export { EMPTY_SPECIALTY } from './specialty';
